name: Run tests with miniconda
on: [push]

jobs:
  test:
    name: Miniconda ${{ matrix.os }} Py${{ matrix.pyver }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
            pyver: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
#          environment-file: environment.yml
          python-version: ${{ matrix.pyver }}
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
      - name: Run pytest
        shell: bash -l {0}
        run: |
            conda install --file conda_requirements.txt --file conda_requirements_test.txt
            pip install -e .
            cd ..
            pytest --pyargs gridded

  lint:
    name: Flake8 linting
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: lint
          python-version: 3.9
          auto-activate-base: false
      - shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
      - name: Lint
        shell: bash -l {0}
        run: |
            conda install flake8
            python -m flake8 --statistics gridded/
